### ISSUE TITLE
pub dev release?

### ISSUE THREAD

**Issue by akadatsky** [lukehutch/flutter_reactive_widget#1]
Hello, is this plugin already released on pub.dev?
I come here from https://docs.flutter.dev/development/data-and-backend/state-mgmt/options
and find this plugin nice, but is it already production redy?

**Comment by lukehutch** [comment]
I haven't released this in pub.dev yet, because the code is brand new, and hasn't been tested by anyone but me. It works flawlessly for me, and I'm actively using it in a number of places in a large app I'm developing, but I really need some testers. I'm you're willing to take the (hopefully minor) risk of using this, I'd love to hear your experiences.

**Comment by akadatsky** [comment]
@lukehutch I played a bit with this project and found some places which may be improved:
1) example should contain complete project with the Android/iOS part, not just 1 file
2) for me example does not work - it shows the error:

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building ReactiveWidget(dirty, state: _ReactiveWidgetState#6eac9):
Need to call `await PersistentReactiveValue.init()` first
'package:flutter_reactive_widget/src/persistent_reactive_value.dart':
Failed assertion: line 19 pos 12: '_storage != null'
```

3) I tried this plugin in my project but was not successful: 
The idea was to update the value in Appbar when the user selects another date on the calendar.
I trigger value changes but ReactiveWidget does not rebuild. 
Probably I did something wrong, the code was something like this:

```
class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final observer = ReactiveValue<DateTime>(DateTime.now());

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 0,
        centerTitle: false,
        title: ReactiveWidget(
              () => Text(DateFormat.yMMMd().format(observer.value)),
        ),
        backgroundColor: const Color.fromARGB(255, 71, 123, 171),
      ),
      body: CalendarPager(
        controller: CalendarPagerController(DateTime.now()),
        builder: (date, isMorning) {
          observer.value = date;
          return Container();
        },
      ),
    );
  }
}
```

**Comment by lukehutch** [comment]
> 1. example should contain complete project with the Android/iOS part, not just 1 file

You're right... I am super busy working on my actual app though, I just threw this library out there because I find it super useful. Hopefully I'll find time in the future to work more on packaging it up in a better way.

The example is really just the minimal possible example of how to use this library, so it's more there so you can just read the code, I didn't think anyone would try to run it!

> 2. for me example does not work - it shows the error:

Thanks, I don't know how that snuck in there. I added the initialization code to `main()` as specified in the docs.

> 3. I tried this plugin in my project but was not successful:
>    The idea was to update the value in Appbar when the user selects another date on the calendar.
>    I trigger value changes but ReactiveWidget does not rebuild.
>    Probably I did something wrong, the code was something like this:

Hmm, this is pretty interesting. My first guess would be that the way to fix it would be to put the `ReactiveWidget` around the `AppBar`, rather than around the title. Does that work for you?

If so, I have no idea why `title`'s widget doesn't update dynamically, but it is probably worth a bug report to the Flutter github repo, since any widget in the tree should be allowed to be a `StatefulWidget` (which `ReactiveWidget` subclasses) that can change its state based on calling `setState()` (this is what `ReactiveWidget` does when the value it is watching changes).

Let me know if the above change solves the problem. It's possible that the Flutter team forgot to propagate state change requests through the `title` field of `AppBar`, or something...

**Comment by lukehutch** [comment]
I saw somebody else complaining about something similar on StackOverflow, and the suggested solution was to wrap the outermost `Scaffold` in a `StatefulWidget` and calling `setState`. So if wrapping `AppBar` with `ReactiveWidget` doesn't work, try wrapping `Scaffold` instead.

**Comment by akadatsky** [comment]
Thanks for your time, I sent a pull request with a complete example - accept it if you like, or not if you want to keep things simple. 
I can't wrap AppBar with ReactiveWidget cause it requires PreferredSizeWidget, and I don't want to wrap Scaffold cause that was exactly what I was trying to avoid by using this package: rebuild all screen on every change.

**Comment by lukehutch** [comment]
Please try wrapping Scaffold just so we can debug the issue. If it works, then there is (probably) a bug in Flutter. If not, there is (possibly) a bug in this library.

**Comment by lukehutch** [comment]
PS thanks for the complete example!

**Comment by lukehutch** [comment]
I published this library to pub.dev.

https://pub.dev/packages/flutter_reactive_widget

**Comment by lukehutch** [comment]
Hey, I came up with a much better and simpler way to do reactivity in Flutter -- check it out:

https://github.com/lukehutch/flutter_reactive_value

(The `flutter_reactive_widget` library is now deprecated, since the new solution is so much better.)
